/**
 * Compares strings by their Unicode code-point sequence.
 *
 * Unlike locale-aware comparison, this ordering is independent of the host's
 * locale and ICU data, so generated bytes and persisted state remain stable.
 */
export function compareCodePoints(left: string, right: string): number {
  const leftCodePoints = Array.from(left);
  const rightCodePoints = Array.from(right);
  const length = Math.min(leftCodePoints.length, rightCodePoints.length);
  for (let index = 0; index < length; index += 1) {
    const leftValue = leftCodePoints[index]?.codePointAt(0);
    const rightValue = rightCodePoints[index]?.codePointAt(0);
    if (leftValue === undefined || rightValue === undefined) {
      break;
    }
    if (leftValue !== rightValue) {
      return leftValue < rightValue ? -1 : 1;
    }
  }
  return leftCodePoints.length - rightCodePoints.length;
}
